import type {CanvasData} from "../canvas/types";

/** Example 2 & 3: Variable injection and Python state. */
export function getExample4CanvasData(): CanvasData {
	return {
		nodes: [
			// Workflow 2: Variable Injection
			{
				id: "group-inject",
				type: "group",
				x: 30,
				y: 30,
				width: 720,
				height: 540,
				label: "Workflow 2: Variable Injection (precise placement)",
			},
			{
				id: "yellow-concept",
				type: "text",
				text: "Evergreen notes",
				x: 50,
				y: 100,
				width: 200,
				height: 60,
				color: "3",
			},
			{
				id: "orange-define",
				type: "text",
				text: "Define {{var:term}} in one sentence.",
				x: 300,
				y: 100,
				width: 250,
				height: 100,
				color: "1",
			},
			{
				id: "purple-critique",
				type: "text",
				text: "Critique this definition:\n\n{{var:def}}\n\nProvide 2 improvements.",
				x: 300,
				y: 260,
				width: 300,
				height: 140,
				color: "2",
			},
			{
				id: "note-inject-explanation",
				type: "text",
				text: "💡 How it works:\n\n1. Label the edge: 'term' (not concatenated)\n2. In Orange: {{var:term}} inserts 'Evergreen notes'\n3. Label next edge: 'def' \n4. In Purple: {{var:def}} inserts the definition\n\nWithout {{var:name}}, the input would be concatenated at the top instead.",
				x: 50,
				y: 430,
				width: 650,
				height: 120,
				color: "",
			},
			// Workflow 3: Python State
			{
				id: "group-python",
				type: "group",
				x: 30,
				y: 610,
				width: 720,
				height: 520,
				label: "Workflow 3: Python Persistent State",
			},
			{
				id: "yellow-note1",
				type: "text",
				text: "Topic: Atomic notes",
				x: 50,
				y: 680,
				width: 200,
				height: 60,
				color: "3",
			},
			{
				id: "blue-store1",
				type: "text",
				text: "# Init shared state\nif 'notes' not in globals():\n    notes = []\n\nnotes.append(input)\nprint(f\"Stored: {input}\")\nobsidian_log(f\"Total notes: {len(notes)}\")",
				x: 50,
				y: 780,
				width: 280,
				height: 180,
				color: "6",
			},
			{
				id: "yellow-note2",
				type: "text",
				text: "Topic: Progressive summarization",
				x: 400,
				y: 680,
				width: 200,
				height: 60,
				color: "3",
			},
			{
				id: "blue-store2",
				type: "text",
				text: "# Reuse state\nnotes.append(input)\nprint(f\"Stored: {input}\")\nobsidian_log(f\"Total notes: {len(notes)}\")",
				x: 370,
				y: 780,
				width: 280,
				height: 140,
				color: "6",
			},
			{
				id: "blue-summarize",
				type: "text",
				text: "# Access accumulated data\nfor i, note in enumerate(notes, 1):\n    print(f\"{i}. {note}\")\n\nprint(f\"\\nCollected {len(notes)} note topics\")",
				x: 180,
				y: 990,
				width: 350,
				height: 120,
				color: "6",
			},
			{
				id: "note-python-explanation",
				type: "text",
				text: "💡 How it works:\n\nPython kernel persists per canvas. Variables like 'notes' survive across runs.\n\nobsidian_log() sends to side panel (open via ribbon).",
				x: 50,
				y: 1000,
				width: 650,
				height: 110,
				color: "",
			},
		],
		edges: [
			// Workflow 2 edges
			{ id: "edge-concept-define", fromNode: "yellow-concept", toNode: "orange-define", label: "term" },
			{ id: "edge-define-critique", fromNode: "orange-define", toNode: "purple-critique", label: "def" },
			// Workflow 3 edges
			{ id: "edge-note1-store1", fromNode: "yellow-note1", toNode: "blue-store1" },
			{ id: "edge-note2-store2", fromNode: "yellow-note2", toNode: "blue-store2" },
			{ id: "edge-store1-summarize", fromNode: "blue-store1", toNode: "blue-summarize" },
			{ id: "edge-store2-summarize", fromNode: "blue-store2", toNode: "blue-summarize" },
		],
	};
}
